// async function hideVoca(i) {
//     const res = await fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1')
//         .then(res => res.json())
//     let data = res[0].data
//     data[i].checked = true

//     let b = {
//         data: data
//     }

//     // fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1/1', {
//     //     method: 'PUT',
//     //     headers: {
//     //         'Content-Type': 'application/json'
//     //     },
//     //     body: JSON.stringify(b)
//     // })


//     // OK Roi do
//     // Tiep theo la: sau 10 lan clickc thi put 1 lan
// }

let app = document.querySelector('.app')
let vocabulary = null
let count = 0

async function hideVoca(i) {
    count++
    vocabulary[i].checked = true
    if (count === 10) {
        let b = {
            data: vocabulary
        }
        count = 0
        const res = await fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1/1', {
            method: 'PUT',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(b)
        })
        run()
    }
}

async function run() {
    async function getDdata() {
        const res = await fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1')
            .then(res => res.json())
        let data = res[0].data
        return data
    }
    vocabulary = await getDdata()

    vocabulary.forEach((e, index) => {
        let item = document.createElement('div')
        item.classList.add('item')
        e.checked && item.classList.add('hide')


        let content = '<p class="count">' + index + '</p>'
            + '<h6 class="vocabulary">' + e.voca + '</h6>'
            + '<p class="meaning">' + e.mean + '</p>'
            + '<input type="checkbox" onclick="hideVoca(' + index + ')">'
        item.innerHTML = content
        app.append(item)
    });

}

run()


// fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1/1', {
//     method: 'PUT',
//     headers: {
//         'Content-Type': 'application/json'
//     },
//     body: JSON.stringify(data)
// })


// let a = [
//     "new",
//     "mới",
//     "company",
//     "công ty",
//     "Mr.",
//     "ông",
//     "year",
//     "năm",
//     "service",
//     "dịch vụ",
//     "please",
//     "vui lòng",
//     "customer",
//     "khách hàng",
//     "work",
//     "làm việc / công việc",
//     "email",
//     "thư điện tử",
//     "Ms.",
//     "bà",
//     "make",
//     "làm",
//     "more",
//     "thêm / nhiều hơn",
//     "time",
//     "thời gian / thời điểm",
//     "product",
//     "sản phẩm",
//     "business",
//     "kinh doanh / doanh nghiệp",
//     "day",
//     "ngày",
//     "employee",
//     "nhân viên",
//     "use",
//     "sử dụng",
//     "information",
//     "thông tin",
//     "member",
//     "thành viên",
//     "order",
//     "đơn hàng / đặt hàng",
//     "letter",
//     "lá thư",
//     "provide",
//     "cung cấp",
//     "date",
//     "ngày",
//     "receive",
//     "nhận",
//     "office",
//     "văn phòng",
//     "manage",
//     "quản lý",
//     "month",
//     "tháng",
//     "most",
//     "nhiều nhất / hầu hết",
//     "also",
//     "cũng",
//     "hotel",
//     "khách sạn",
//     "include",
//     "bao gồm",
//     "than",
//     "so với",
//     "only",
//     "chỉ",
//     "price",
//     "giá",
//     "purchase",
//     "mua",
//     "other",
//     "khác",
//     "week",
//     "tuần",
//     "thank",
//     "cám ơn",
//     "send",
//     "gửi",
//     "plan",
//     "kế hoạch / lên kế hoạch",
//     "open",
//     "mở",
//     "contact",
//     "liên lạc",
//     "change",
//     "thay đổi",
//     "add",
//     "thêm",
//     "store",
//     "cửa hàng",
//     "article",
//     "bài báo",
//     "call",
//     "gọi",
//     "schedule",
//     "lịch trình / lên lịch",
//     "event",
//     "sự kiện",
//     "first",
//     "đầu tiên / thứ nhất",
//     "center",
//     "trung tâm",
//     "free",
//     "miễn phí / tự do",
//     "ask",
//     "hỏi / yêu cầu",
//     "like",
//     "thích",
//     "next",
//     "tiếp theo",
//     "request",
//     "yêu cầu",
//     "job",
//     "việc làm / công việc",
//     "before",
//     "trước",
//     "department",
//     "bộ phận",
//     "after",
//     "sau",
//     "design",
//     "thiết kế",
//     "city",
//     "thành phố",
//     "number",
//     "số / số lượng",
//     "high",
//     "cao",
//     "need",
//     "cần",
//     "conference",
//     "hội nghị",
//     "know",
//     "biết",
//     "meeting",
//     "cuộc họp",
//     "give",
//     "đưa / đưa ra",
//     "special",
//     "đặc biệt",
//     "staff",
//     "nhân viên",
//     "room",
//     "phòng",
//     "announce",
//     "thông báo",
//     "website",
//     "trang web",
//     "write",
//     "viết",
//     "visit",
//     "ghé thăm / chuyến đi",
//     "hour",
//     "giờ",
//     "require",
//     "yêu cầu",
//     "help",
//     "giúp đỡ",
//     "because",
//     "bởi vì",
//     "increase",
//     "tăng",
//     "people",
//     "người",
//     "find",
//     "tìm thấy / cảm thấy",
//     "complete",
//     "hoàn thành / hoàn chỉnh",
//     "attend",
//     "tham dự",
//     "program",
//     "chương trình",
//     "book",
//     "sách",
//     "according to",
//     "theo như",
//     "many",
//     "nhiều",
//     "food",
//     "đồ ăn / thực phẩm",
//     "travel",
//     "đi lại / du lịch",
//     "last",
//     "vừa qua / trước",
//     "current",
//     "hiện tại",
//     "project",
//     "dự án",
//     "report",
//     "báo cáo",
//     "form",
//     "mẫu (đơn)",
//     "follow",
//     "theo sau / làm theo",
//     "area",
//     "khu vực",
//     "during",
//     "trong suốt",
//     "experience",
//     "kinh nghiệm",
//     "notice",
//     "chú ý / thông báo",
//     "team",
//     "đội / nhóm",
//     "pay",
//     "chi trả",
//     "cost (n)",
//     "chi phí",
//     "march",
//     "tháng Ba",
//     "computer",
//     "máy tính",
//     "come",
//     "đến",
//     "very",
//     "rất",
//     "june",
//     "tháng Sáu",
//     "see",
//     "xem / thấy",
//     "problem",
//     "vấn đề",
//     "deliver",
//     "giao (hàng...)",
//     "each",
//     "mỗi",
//     "want",
//     "muốn",
//     "start",
//     "bắt đầu",
//     "submit",
//     "nộp",
//     "large",
//     "lớn",
//     "home",
//     "nhà",
//     "say",
//     "nói",
//     "hope",
//     "hy vọng",
//     "there is",
//     "có",
//     "where",
//     "nơi nào / nơi mà",
//     "card",
//     "thẻ",
//     "register",
//     "đăng ký",
//     "expect",
//     "trông đợi",
//     "able",
//     "có thể",
//     "best",
//     "tốt nhất",
//     "ticket",
//     "vé",
//     "develop",
//     "phát triển",
//     "now",
//     "bây giờ",
//     "august",
//     "tháng Tám",
//     "director",
//     "giám đốc",
//     "april",
//     "tháng Tư",
//     "get",
//     "có được / lấy",
//     "name",
//     "tên",
//     "question",
//     "câu hỏi",
//     "july",
//     "tháng Bảy",
//     "much",
//     "nhiều",
//     "take",
//     "lấy / mang",
//     "ship",
//     "giao (hàng)",
//     "begin",
//     "bắt đầu",
//     "research",
//     "nghiên cứu",
//     "advertise",
//     "quảng cáo",
//     "charge",
//     "phí / tính phí",
//     "long",
//     "dài / lâu",
//     "return",
//     "trả lại / trở lại",
//     "hold",
//     "tổ chức",
//     "while",
//     "trong khi",
//     "review",
//     "xem lại / đánh giá",
//     "every",
//     "mỗi",
//     "mention",
//     "đề cập",
//     "system",
//     "hệ thống",
//     "class",
//     "lớp học",
//     "into",
//     "vào trong",
//     "training",
//     "đào tạo / huấn luyện",
//     "group",
//     "nhóm",
//     "restaurant",
//     "nhà hàng",
//     "health",
//     "sức khỏe",
//     "full",
//     "đầy đủ / toàn bộ",
//     "main",
//     "chính / chủ yếu",
//     "part",
//     "phần",
//     "read",
//     "đọc",
//     "construction",
//     "xây dựng",
//     "international",
//     "quốc tế",
//     "success",
//     "sự thành công",
//     "contract",
//     "hợp đồng",
//     "fee",
//     "khoản phí",
//     "quality",
//     "chất lượng",
//     "client",
//     "khách hàng",
//     "university",
//     "trường đại học",
//     "close",
//     "gần / gần gũi",
//     "within",
//     "trong vòng",
//     "repair",
//     "sửa chữa",
//     "september",
//     "tháng Chín",
//     "end",
//     "kết thúc / cuối",
//     "participate",
//     "tham gia",
//     "interview",
//     "buổi phỏng vấn",
//     "building",
//     "tòa nhà",
//     "however",
//     "tuy nhiên",
//     "student",
//     "sinh viên",
//     "list",
//     "danh sách / liệt kê",
//     "publish",
//     "xuất bản",
//     "result",
//     "kết quả",
//     "arrive",
//     "đến",
//     "both",
//     "cả hai",
//     "confirm",
//     "xác nhận",
//     "until",
//     "cho đến khi",
//     "inform",
//     "thông báo cho",
//     "technology",
//     "công nghệ",
//     "monday",
//     "thứ Hai",
//     "discuss",
//     "bàn bạc / thảo luận",
//     "just",
//     "chỉ / vừa mới",
//     "october",
//     "tháng Mười",
//     "good",
//     "tốt",
//     "car",
//     "xe hơi",
//     "let",
//     "cho / để",
//     "street",
//     "đường",
//     "hire",
//     "thuê",
//     "copy",
//     "bản sao / sao chép",
//     "few",
//     "ít / vài",
//     "important",
//     "quan trọng",
//     "small",
//     "nhỏ",
//     "magazine",
//     "tạp chí",
//     "art",
//     "nghệ thuật",
//     "address",
//     "địa chỉ",
//     "sell",
//     "bán",
//     "consider",
//     "xem xét",
//     "meet",
//     "gặp",
//     "water",
//     "nước",
//     "world",
//     "thế giới",
//     "apply",
//     "nộp đơn xin",
//     "equipment",
//     "thiết bị",
//     "trip",
//     "chuyến đi",
//     "account",
//     "tài khoản",
//     "great",
//     "tuyệt vời / rất lớn",
//     "opportunity",
//     "cơ hội",
//     "guest",
//     "khách",
//     "meaning",
//     "ý nghĩa",
//     "note",
//     "chú ý / ghi chú",
//     "photograph",
//     "bức ảnh",
//     "skill",
//     "kỹ năng",
//     "benefit",
//     "lợi ích / có lợi",
//     "rent",
//     "thuê",
//     "flight",
//     "chuyến bay",
//     "president",
//     "chủ tịch",
//     "airport",
//     "sân bay",
//     "accept",
//     "chấp nhận",
//     "january",
//     "tháng Một",
//     "improve",
//     "cải thiện",
//     "february",
//     "tháng Hai",
//     "allow",
//     "cho phép",
//     "support",
//     "hỗ trợ / ủng hộ",
//     "bring",
//     "mang",
//     "friday",
//     "thứ Sáu",
//     "become",
//     "trở nên",
//     "policy",
//     "chính sách",
//     "convenient",
//     "tiện lợi",
//     "museum",
//     "bảo tàng",
//     "december",
//     "tháng Mười Hai",
//     "tour",
//     "chuyến tham quan / du lịch",
//     "sure",
//     "chắc chắn / đảm bảo",
//     "choose",
//     "chọn",
//     "environment",
//     "môi trường",
//     "win",
//     "chiến thắng",
//     "november",
//     "tháng Mười Một",
//     "clean",
//     "sạch / làm sạch",
//     "buy",
//     "mua",
//     "between",
//     "giữa",
//     "park",
//     "công viên",
//     "bank",
//     "ngân hàng",
//     "different",
//     "khác",
//     "look forward",
//     "trông đợi",
//     "space",
//     "không gian / chỗ",
//     "build",
//     "xây dựng",
//     "in order to",
//     "để (làm gì đó)",
//     "electronic",
//     "điện tử",
//     "saturday",
//     "thứ Bảy",
//     "country",
//     "đất nước",
//     "personal",
//     "cá nhân",
//     "reduce",
//     "giảm",
//     "money",
//     "tiền",
//     "create",
//     "tạo ra",
//     "final",
//     "cuối cùng",
//     "introduce",
//     "giới thiệu",
//     "percent",
//     "phần trăm",
//     "expand",
//     "mở rộng",
//     "worker",
//     "công nhân / nhân viên",
//     "future",
//     "tương lai",
//     "again",
//     "một lần nữa / lại",
//     "serve",
//     "phục vụ",
//     "move",
//     "di chuyển / di dời",
//     "true",
//     "đúng / thật sự",
//     "family",
//     "gia đình",
//     "past",
//     "qua / quá khứ",
//     "professional",
//     "chuyên nghiệp / người chuyên nghiệp",
//     "low",
//     "thấp",
//     "parking",
//     "đỗ xe",
//     "show",
//     "cho thấy",
//     "early",
//     "sớm",
//     "enjoy",
//     "tận hưởng / thích",
//     "print",
//     "in",
//     "although",
//     "mặc dù",
//     "today",
//     "hôm nay",
//     "seminar",
//     "hội thảo",
//     "document",
//     "tài liệu",
//     "regular",
//     "thường xuyên / thường",
//     "place",
//     "nơi / chỗ",
//     "safe",
//     "an toàn",
//     "soon",
//     "sớm",
//     "children",
//     "trẻ em",
//     "back",
//     "lại / trở lại",
//     "school",
//     "trường học",
//     "think",
//     "nghĩ",
//     "invest",
//     "đầu tư",
//     "limit",
//     "giới hạn",
//     "house",
//     "nhà",
//     "over",
//     "hơn",
//     "care",
//     "chăm sóc / quan tâm",
//     "minute",
//     "phút",
//     "keep",
//     "giữ",
//     "sales",
//     "doanh thu",
//     "since",
//     "từ khi",
//     "compete",
//     "cạnh tranh",
//     "total",
//     "tổng cộng",
//     "near",
//     "gần",
//     "produce",
//     "sản xuất / tạo ra",
//     "around",
//     "xung quanh / khoảng",
//     "close",
//     "đóng",
//     "bill",
//     "hóa đơn",
//     "attach",
//     "đính kèm",
//     "prepare",
//     "chuẩn bị",
//     "software",
//     "phần mềm",
//     "human",
//     "người",
//     "encourage",
//     "khuyến khích",
//     "hear",
//     "nghe",
//     "decide",
//     "quyết định (v)",
//     "join",
//     "gia nhập",
//     "there",
//     "ở đó",
//     "select",
//     "chọn",
//     "history",
//     "lịch sử",
//     "summer",
//     "mùa hè",
//     "stay",
//     "ở",
//     "check",
//     "kiểm tra / xem",
//     "ago",
//     "trước đây",
//     "same",
//     "cùng / giống nhau",
//     "learn",
//     "học",
//     "continue",
//     "tiếp tục",
//     "still",
//     "vẫn",
//     "telephone",
//     "điện thoại",
//     "nation",
//     "quốc gia",
//     "arrange",
//     "sắp xếp",
//     "news",
//     "tin tức",
//     "bus",
//     "xe buýt",
//     "under",
//     "dưới",
//     "page",
//     "trang",
//     "invite",
//     "mời",
//     "thursday",
//     "thứ Năm",
//     "feel",
//     "cảm thấy",
//     "message",
//     "tin nhắn",
//     "night",
//     "đêm",
//     "second",
//     "thứ hai",
//     "theater",
//     "nhà hát / rạp phim",
//     "tell",
//     "nói",
//     "old",
//     "cũ / lớn tuổi",
//     "necessary",
//     "cần thiết",
//     "amount",
//     "số lượng / khoản (tiền...)",
//     "presentation",
//     "buổi thuyến trình",
//     "library",
//     "thư viện",
//     "government",
//     "chính phủ",
//     "club",
//     "câu lạc bộ",
//     "road",
//     "đường",
//     "economy",
//     "kinh tế",
//     "way",
//     "cách",
//     "floor",
//     "tầng / sàn nhà",
//     "monthly",
//     "hàng tháng",
//     "sunday",
//     "Chủ Nhật",
//     "here",
//     "ở đây",
//     "organization",
//     "tổ chức",
//     "better",
//     "tốt hơn",
//     "shop",
//     "cửa hàng",
//     "shopping",
//     "mua sắm",
//     "level",
//     "mức độ / cấp độ",
//     "excellent",
//     "tuyệt vời",
//     "vehicle",
//     "xe",
//     "idea",
//     "ý tưởng",
//     "less",
//     "ít hơn",
//     "later",
//     "sau đó / trễ hơn",
//     "always",
//     "luôn luôn",
//     "machine",
//     "máy",
//     "describe",
//     "mô tả",
//     "morning",
//     "buổi sáng",
//     "immediately",
//     "ngay lập tức",
//     "install",
//     "lắp đặt / cài đặt",
//     "live",
//     "sống",
//     "enter",
//     "đi vào / đưa vào",
//     "without",
//     "không có",
//     "train",
//     "xe lửa",
//     "film",
//     "phim",
//     "coupon",
//     "phiếu giảm giá",
//     "size",
//     "kích thước / kích cỡ",
//     "accounting",
//     "kế toán",
//     "meal",
//     "bữa ăn",
//     "try",
//     "cố gắng / thử",
//     "cancel",
//     "hủy",
//     "drive",
//     "lái xe",
//     "vacation",
//     "kỳ nghỉ",
//     "complain",
//     "phàn nàn",
//     "reason",
//     "lí do",
//     "gift",
//     "quà tặng",
//     "sign",
//     "ký",
//     "spend",
//     "chi tiêu / dành (thời gian)",
//     "speak",
//     "nói / phát biểu",
//     "factory",
//     "nhà máy",
//     "welcome",
//     "chào đón",
//     "season",
//     "mùa",
//     "top",
//     "hàng đầu / trên cùng",
//     "appointment",
//     "cuộc hẹn",
//     "run",
//     "chạy",
//     "music",
//     "âm nhạc",
//     "air",
//     "không khí / hàng không",
//     "wednesday",
//     "thứ Tư",
//     "quickly",
//     "nhanh chóng",
//     "station",
//     "trạm / đài",
//     "attract",
//     "thu hút",
//     "weekend",
//     "cuối tuần",
//     "like",
//     "giống",
//     "well",
//     "tốt",
//     "activity",
//     "hoạt động",
//     "organize",
//     "tổ chức / sắp xếp",
//     "look for",
//     "tìm kiếm",
//     "tuesday",
//     "thứ Ba",
//     "then",
//     "sau đó",
//     "might",
//     "có thể",
//     "explain",
//     "giải thích",
//     "visitor",
//     "khách / du khách",
//     "display",
//     "trưng bày",
//     "believe",
//     "tin",
//     "delay",
//     "trì hoãn",
//     "wide",
//     "rộng",
//     "paper",
//     "giấy",
//     "strong",
//     "mạnh",
//     "test",
//     "kiểm tra",
//     "web",
//     "mạng",
//     "desk",
//     "cái bàn",
//     "life",
//     "cuộc sống / cuộc đời",
//     "leave",
//     "rời đi / rời khỏi",
//     "comment",
//     "lời bình",
//     "teach",
//     "dạy",
//     "book",
//     "đặt (phòng, vé...)",
//     "course",
//     "khóa học",
//     "lost",
//     "mất",
//     "late",
//     "trễ",
//     "decision",
//     "quyết định (n)",
//     "retire",
//     "về hưu",
//     "festival",
//     "lễ hội",
//     "tourist",
//     "khách du lịch",
//     "drink",
//     "uống / đồ uống",
//     "party",
//     "bữa tiệc",
//     "relations",
//     "quan hệ",
//     "America",
//     "nước Mỹ",
//     "someone",
//     "ai đó",
//     "garden",
//     "vườn",
//     "volunteer",
//     "người tình nguyện",
//     "person",
//     "người",
//     "responsible",
//     "chịu trách nhiệm",
//     "sport",
//     "thể thao",
//     "hospital",
//     "bệnh viện",
//     "happen",
//     "xảy ra",
//     "wish",
//     "muốn",
//     "down",
//     "xuống",
//     "too",
//     "quá",
//     "million",
//     "triệu",
//     "camera",
//     "máy ảnh / máy quay phim",
//     "Asia",
//     "châu Á",
//     "often",
//     "thường xuyên",
//     "answer",
//     "trả lời",
//     "demand",
//     "nhu cầu",
//     "put",
//     "đặt / để",
//     "happy",
//     "vui",
//     "front",
//     "trước",
//     "movie",
//     "bộ phim",
//     "seat",
//     "chỗ ngồi",
//     "protect",
//     "bảo vệ",
//     "difficult",
//     "khó khăn",
//     "talk",
//     "nói chuyện",
//     "kitchen",
//     "nhà bếp",
//     "lunch",
//     "bữa trưa",
//     "maintain",
//     "duy trì / bảo trì",
//     "easy",
//     "dễ dàng",
//     "away",
//     "xa",
//     "dinner",
//     "bữa tối",
//     "television / TV",
//     "truyền hình / tivi",
//     "wait",
//     "chờ",
//     "rise",
//     "tăng",
//     "avoid",
//     "tránh",
//     "understand",
//     "hiểu",
//     "color",
//     "màu sắc",
//     "deadline",
//     "hạn chót",
//     "goal",
//     "mục tiêu",
//     "post",
//     "đăng",
//     "contain",
//     "chứa đựng",
//     "agree",
//     "đồng ý",
//     "finish",
//     "hoàn thành",
//     "enough",
//     "đủ",
//     "newspaper",
//     "báo",
//     "look",
//     "nhìn",
//     "simple",
//     "đơn giản",
//     "performance",
//     "buổi biểu diễn",
//     "expensive",
//     "đắt tiền",
//     "afternoon",
//     "buổi chiều",
//     "menu",
//     "thực đơn",
//     "grow",
//     "gia tăng / phát triển",
//     "together",
//     "cùng / cùng nhau",
//     "coffee",
//     "cà phê",
//     "short",
//     "ngắn",
//     "branch",
//     "chi nhánh",
//     "real",
//     "thực sự",
//     "famous",
//     "nổi tiếng",
//     "daily",
//     "hàng ngày",
//     "weather",
//     "thời tiết",
//     "everyone",
//     "mọi người",
//     "advice",
//     "lời khuyên",
//     "friend",
//     "người bạn",
//     "friendly",
//     "thân thiện",
//     "big",
//     "lớn",
//     "never",
//     "không bao giờ",
//     "box",
//     "hộp",
//     "swimming pool",
//     "hồ bơi",
//     "outside",
//     "bên ngoài",
//     "salary",
//     "tiền lương",
//     "responsibility",
//     "trách nhiệm",
//     "fast",
//     "nhanh",
//     "anyone",
//     "bất kỳ ai",
//     "carefully",
//     "cẩn thận",
//     "style",
//     "phong cách",
//     "remind",
//     "nhắc nhở",
//     "ability",
//     "khả năng",
//     "adult",
//     "người lớn",
//     "cook",
//     "nấn ăn",
//     "save",
//     "tiết kiệm",
//     "a lot of",
//     "nhiều",
//     "clear",
//     "rõ ràng",
//     "game",
//     "trò chơi",
//     "graduate",
//     "tốt nghiệp",
//     "share",
//     "chia sẻ",
//     "walk",
//     "đi bộ",
//     "beautiful",
//     "đẹp",
//     "hold",
//     "giữ",
//     "yesterday",
//     "hôm qua",
//     "knowledge",
//     "kiến thức",
//     "table",
//     "cái bàn",
//     "picture",
//     "bức ảnh",
//     "holiday",
//     "kỳ nghỉ / lỳ lễ",
//     "culture",
//     "văn hóa",
//     "half",
//     "nửa",
//     "correct",
//     "đúng / chỉnh sửa",
//     "paint",
//     "sơn",
//     "usually",
//     "thường xuyên",
//     "last",
//     "cuối cùng",
//     "error",
//     "lỗi",
//     "comfortable",
//     "thoải mái",
//     "wedding",
//     "đám cưới",
//     "traveler",
//     "hành khách",
//     "printer",
//     "máy in",
//     "ready",
//     "sẵn sàng",
//     "everything",
//     "mọi thứ",
//     "clothing",
//     "quần áo",
//     "fashion",
//     "thời trang",
//     "topic",
//     "chủ đề",
//     "exercise",
//     "tập (thể dục)",
//     "sorry",
//     "xin lỗi / tiếc",
//     "eat",
//     "ăn",
//     "third",
//     "thứ ba / một phần ba",
//     "door",
//     "cửa",
//     "gym",
//     "phòng tập thể dục",
//     "wear",
//     "mặc / mang",
//     "young",
//     "trẻ",
//     "perfect",
//     "hoàn hảo",
//     "electricity",
//     "điện",
//     "evening",
//     "buổi tối",
//     "things",
//     "thứ / điều",
//     "men",
//     "đàn ông",
//     "stop",
//     "dừng / điểm dừng",
//     "breakfast",
//     "bữa sáng",
//     "reply",
//     "trả lời",
//     "cut",
//     "cắt / cắt giảm",
//     "step",
//     "bước",
//     "weekly",
//     "hàng tuần",
//     "suitable",
//     "phù hợp",
//     "search",
//     "tìm kiếm",
//     "play",
//     "chơi",
//     "right",
//     "đúng",
//     "dollar",
//     "đô la",
//     "opinion",
//     "ý kiến",
//     "seem",
//     "có vẻ như",
//     "cooperation",
//     "sự hợp tác",
//     "example",
//     "ví dụ",
//     "band",
//     "ban nhạc",
//     "resort",
//     "khu nghỉ mát",
//     "age",
//     "tuổi",
//     "on time",
//     "đúng giờ",
//     "little",
//     "ít",
//     "traffic",
//     "giao thông",
//     "key",
//     "chìa khóa / then chốt",
//     "prize",
//     "giải thưởng",
//     "woman",
//     "phụ nữ",
//     "mobile",
//     "di động",
//     "heavy",
//     "nặng / lớn",
//     "tomorrow",
//     "ngày mai",
//     "busy",
//     "bận rộn",
//     "bag",
//     "túi / túi xách",
//     "face",
//     "mặt / đối mặt",
//     "white",
//     "màu trắng",
//     "blue",
//     "xanh dương",
//     "advise",
//     "khuyên / thông báo",
//     "story",
//     "câu chuyện",
//     "useful",
//     "hữu ích",
//     "black",
//     "màu đen",
//     "river",
//     "con sông",
//     "depend",
//     "phụ thuộc",
//     "compare",
//     "so sánh",
//     "lake",
//     "hồ",
//     "wine",
//     "rượu vang",
//     "mistake",
//     "lỗi lầm / nhầm lẫn",
//     "farm",
//     "nông trại",
//     "mean",
//     "có nghĩa",
//     "hand",
//     "tay",
//     "brown",
//     "màu nâu",
//     "flower",
//     "hoa",
//     "image",
//     "hình ảnh",
//     "inside",
//     "bên trong",
//     "swimming",
//     "bơi",
//     "wash",
//     "giặt / rửa",
//     "hard",
//     "chăm chỉ",
//     "doctor",
//     "bác sĩ",
//     "discussion",
//     "buổi thảo luận",
//     "modern",
//     "hiện đại",
//     "action",
//     "hành động",
//     "mountain",
//     "ngọn núi",
//     "perform",
//     "biểu diễn",
//     "vegetables",
//     "rau",
//     "beside",
//     "bên cạnh",
//     "cake",
//     "bánh",
//     "fly",
//     "bay",
//     "winter",
//     "mùa đông",
//     "remember",
//     "nhớ",
//     "red",
//     "màu đỏ",
//     "behind",
//     "phía sau",
//     "boat",
//     "con thuyền",
//     "uniform",
//     "đồng phục",
//     "chair",
//     "ghế",
//     "automatic",
//     "tự động",
//     "congratulations",
//     "chúc mừng",
//     "watch",
//     "xem",
//     "way",
//     "đường",
//     "bed",
//     "cái giường",
//     "light",
//     "ánh sáng / đèn",
//     "foreign",
//     "nước ngoài",
//     "confident",
//     "tự tin",
//     "noon",
//     "trưa",
//     "password",
//     "mật khẩu",
//     "window",
//     "cửa sổ",
//     "United States",
//     "Mỹ",
//     "hot",
//     "nóng",
//     "fun",
//     "vui",
//     "teacher",
//     "giáo viên",
//     "himself",
//     "chính anh ấy / tự anh ấy",
//     "fan",
//     "người hâm mộ",
//     "beach",
//     "bãi biển",
//     "forget",
//     "quên",
//     "calendar",
//     "lịch",
//     "speed",
//     "tốc độ",
//     "study",
//     "học",
//     "cream",
//     "kem",
//     "body",
//     "cơ thể / thân",
//     "shoe",
//     "giày",
//     "fruit",
//     "trái cây",
//     "love",
//     "yêu thích / yêu thương",
//     "plane",
//     "máy bay",
//     "animal",
//     "động vật / con vật",
//     "parent",
//     "cha mẹ",
//     "cheap",
//     "rẻ",
//     "drop",
//     "giảm / rơi",
//     "trust",
//     "tin tưởng",
//     "wall",
//     "bức tường",
//     "green",
//     "xanh",
//     "back",
//     "phía sau",
//     "dry",
//     "khô",
//     "accident",
//     "tai nạn",
//     "sound",
//     "âm thanh",
//     "spring",
//     "mùa xuân",
//     "mind",
//     "tâm trí",
//     "tea",
//     "trà",
//     "truck",
//     "xe tải",
//     "far",
//     "xa",
//     "wish",
//     "chúc",
//     "island",
//     "hòn đảo",
//     "exit",
//     "lối ra",
//     "break",
//     "làm vỡ / phá vỡ",
//     "billion",
//     "một tỷ",
//     "stand",
//     "đứng",
//     "refrigerator",
//     "tủ lạnh",
//     "bike",
//     "xe đạp",
//     "fire",
//     "vụ cháy / chữa cháy",
//     "bedroom",
//     "phòng ngủ",
//     "fine",
//     "tốt",
//     "hello",
//     "chào",
//     "clothes",
//     "quần áo",
//     "hundred",
//     "một trăm",
//     "wrong",
//     "sai",
//     "Mrs.",
//     "bà",
//     "bad",
//     "xấu / tồi tệ",
//     "eye",
//     "mắt",
//     "cheese",
//     "phô mai",
//     "bicycle",
//     "xe đạp",
//     "star",
//     "ngôi sao",
//     "hard",
//     "khó",
//     "map",
//     "bản đồ",
//     "hair",
//     "tóc",
//     "cell phone",
//     "điện thoại di động",
//     "sea",
//     "biển",
//     "shirt",
//     "áo sơ mi",
//     "carry",
//     "mang / mang theo",
//     "twelve",
//     "mười hai",
//     "middle",
//     "giữa",
//     "sometimes",
//     "đôi khi",
//     "bathroom",
//     "phòng tắm",
//     "warm",
//     "ấm",
//     "nothing",
//     "không cái gì",
//     "lesson",
//     "bài học",
//     "actor",
//     "diễn viên",
//     "practice",
//     "luyện tập",
//     "rain",
//     "mưa",
//     "heart",
//     "trái tim",
//     "sit",
//     "ngồi",
//     "myself",
//     "chính tôi",
//     "miss",
//     "cô",
//     "thousand",
//     "một nghìn",
//     "too",
//     "cũng",
//     "rice",
//     "gạo",
//     "ourselves",
//     "chính chúng tôi",
//     "maximum",
//     "tối đa",
//     "kid",
//     "trẻ em",
//     "voice",
//     "giọng nói",
//     "quiet",
//     "yên tĩnh",
//     "apple",
//     "quả táo",
//     "turn off",
//     "tắt",
//     "alone",
//     "chỉ riêng / một mình",
//     "sun",
//     "mặt trời",
//     "listen",
//     "nghe",
//     "draw",
//     "vẽ",
//     "sick",
//     "bị bệnh",
//     "police",
//     "cảnh sát",
//     "anytime",
//     "bất kỳ lúc nào",
//     "zoo",
//     "sở thú",
//     "toy",
//     "đồ chơi",
//     "dream",
//     "ước mơ",
//     "T-shirt",
//     "áo thun",
//     "dish",
//     "đĩa",
//     "ship",
//     "thuyền",
//     "board",
//     "bảng",
//     "post office",
//     "bưu điện",
//     "kind",
//     "tử tế",
//     "let's",
//     "hãy",
//     "waste",
//     "lãng phí",
//     "tour guide",
//     "hướng dẫn viên du lịch",
//     "present",
//     "món quà",
//     "soft",
//     "mềm / nhẹ",
//     "press",
//     "ấn nút",
//     "miss",
//     "nhớ",
//     "right",
//     "bên phải",
//     "glass",
//     "cái ly"
// ]
// let data = []
// for(let i = 0; i < a.length; i++) {
//     let b = {
//         voca: a[i],
//         mean: a[i+ 1]
//     }
//     data = [...data, b]
//     i++
// }
// let b = {
//     data: data
// }

// // fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1').then(res => res.json())
// // .then(res => console.log(res[0].data))



// fetch('https://61986846164fa60017c23067.mockapi.io/Toeic1', {
//     method: 'POST',
//     headers: {
//         'Content-Type': 'application/json'
//     },
//     body: JSON.stringify(b)
// })